- name: delete {{COMPONENT}} directory
  ansible.builtin.file:
    path: "{{ARTIFACT_PATH}}"
    state: absent

- name: create {{COMPONENT}} directory
  ansible.builtin.file:
    path: "{{ARTIFACT_PATH}}"
    state: directory
  become_user: "{{BUSER}}"

## Check if AZ CLI is not there then follow the remaining steps
- name: Check az cli
  shell: which az
  register: out
  ignore_errors: yes

- name: Install AZ CLI
  when: out.rc != 0
  block:
    - name: Copy Azure Repo file
      copy:
        src: az.repo
        dest: /etc/yum.repos.d/az.repo

    - name: Install Azure CLI
      yum:
        name: azure-cli
        state: present

    - name: Install Azure DevOps Extention
      shell: az extension add --name azure-devops

- name: fail here
  shell: "false"

#- name: Configure PAT in AZ CLI
#  shell: echo {{PAT}} | az devops login
#
#- name: Download Artifacts
#  shell: az artifacts universal download --organization https://dev.azure.com/nikkaushal0032/ --project=devops-practise --scope project --feed devops0032 --name "{{component}}" --version {{APP_ARTIFACT_VERSION}} --path .
#  args:
#    chdir: "{{ARTIFACT_PATH}}"


