- name: setup OS Prerquisites
  ansible.builtin.include_tasks: os.yml
- name: install maven packages
  yum:
    name: maven
    state: present
- name: create application user
  ansible.builtin.user:
    name: roboshop

- name: include common role for azure devops artifacts
  ansible.builtin.include_role:
    name: common
    tasks_from: download-from-az-artifacts.yml
  vars:
    ARTIFACT_PATH: "/home/roboshop/{{COMPONENT}}"
    BUSER: "roboshop"

- name: get POM
  copy:
    src: pom.xml
    dest: /home/roboshop/{{COMPONENT}}

- name: compile and build package
  shell:
    chdir: /home/roboshop/{{COMPONENT}}
    cmd: mvn clean package -e
  become_user: roboshop

- name: copy {{COMPONENT}} jar file
  ansible.builtin.copy:
    src: /home/roboshop/shipping/target/shipping-1.0.jar
    dest: /home/roboshop/shipping/shipping.jar
    remote_src: yes

- name: setup systemD service
  ansible.builtin.include_tasks: systemd-setup.yml
