- name: setup OS Prerquisites
  ansible.builtin.include_tasks: os.yml
- name: install maven packages
  ansible.builtin.yum:
    name: maven
    state: present
- name: create application user
  ansible.builtin.user:
    name: roboshop

- name: Download artifacts
  ansible.builtin.include_tasks: download-with-curl.yml

- name: compile and build package
  ansible.builtin.shell:
    chdir: /home/roboshop/{{COMPONENT}}
    cmd: mvn clean package
  become_user: roboshop

- name: copy {{COMPONENT}} jar file
  ansible.builtin.copy:
    src: /home/roboshop/target/shipping-1.0.jar
    dest: /home/roboshop/target/shipping.jar
    remote_src: yes
    
- name: setup systemD service
  ansible.builtin.include_tasks: systemd-setup.yml
