- name: install node js packages
  ansible.builtin.yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present
- name: create application user
  ansible.builtin.user:
    name: roboshop

- name: Download artifacts
  ansible.builtin.include_tasks: download-with-curl.yaml
