- name: setup OS Prerquisites
  ansible.builtin.include_tasks: os.yml

- name: install node js packages
  ansible.builtin.yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present
- name: create application user
  ansible.builtin.user:
    name: roboshop

- name: Download artifacts
  ansible.builtin.include_tasks: download-with-curl.yml
- name: download nodejs (npm) dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
    state: latest
  become_user: roboshop

-name: copy {{COMPONENT}} jar file
 ansible.builtin.copy:
   src: /home/roboshop/target/shipping-1.0.jar
   dest: /home/roboshop/target/shipping.jar
   remote_src: yes
- name: setup systemD service
  ansible.builtin.include_tasks: systemd-setup.yml
