- name: install node js packages
  ansible.builtin.yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present
- name: create application user
  ansible.builtin.user:
    name: roboshop

- name: Download artifacts
  ansible.builtin.include_tasks: download-with-curl.yml
- name: download nodejs (npm) dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
    state: latest
  become_user: roboshop
- name: setup systemD service
  ansible.builtin.include_tasks: systemd-setup.yml
