- name: setup OS Prerquisites
  ansible.builtin.include_tasks: os.yml

- name: install node js packages
  yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present
- name: create application user
  ansible.builtin.user:
    name: roboshop

- name: include common role for azure devops artifacts
  ansible.builtin.include_role:
    name: common
    tasks_from: download-from-az-artifacts.yml
  vars:
    ARTIFACT_PATH: "/home/roboshop/{{COMPONENT}}"
    BUSER: "roboshop"

#- name: download nodejs (npm) dependencies
#  shell: npm install
#  args:
#    chdir: /home/roboshop/{{COMPONENT}}
#  become_user: roboshop

- name: setup systemD service
  ansible.builtin.include_tasks: systemd-setup.yml
