- name: setup OS Prerquisites
  ansible.builtin.include_tasks: os.yml

- name: install python packages
  yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: present
    
- name: create application user
  ansible.builtin.user:
    name: roboshop

- name: include common role for azure devops artifacts
  ansible.builtin.include_role:
    name: common
    tasks_from: download-from-az-artifacts.yml
  vars:
    ARTIFACT_PATH: "/home/roboshop/{{COMPONENT}}"
    BUSER: "roboshop"

- name: Install python packages (python install package)
  ansible.builtin.pip:
    requirements: /home/roboshop/{{COMPONENT}}/requirements.txt
    executable: pip-3

- name: setup systemD service
  ansible.builtin.include_tasks: systemd-setup.yml
