- name: include common role for OS prereqs
  ansible.builtin.include_role:
    name: common
    tasks_from: os

- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: include common role for az devops artifacts
  ansible.builtin.include_role:
    name: common
    tasks_from: download-from-az-artifacts.yml
  vars:
    ARTIFACT_PATH: "/usr/share/nginx"
    BUSER: "root"


- name: rename content directory
  ansible.builtin.shell: mv /usr/share/nginx/static /usr/share/nginx/html

- name: Update nginx configuration
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  notify: Restart nginx

- name: start nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started