- name: include common role for OS prereqs
  ansible.builtin.include_role:
    name: common
    tasks_from: os

- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: include common role for azure devops artifacts
  ansible.builtin.include_role:
    name: common
    tasks_from: download-from-az-artifacts.yml
  vars:
    ARTIFACT_PATH: "/usr/share/nginx"
    BUSER: "root"

- name: delete old content
  ansible.builtin.file:
    path: /usr/share/nginx
    state: absent

- name: create content directory
  ansible.builtin.file:
    path: /usr/share/nginx
    state: directory

- name: download and unzip/unarchive {{COMPONENT}} on a remote machine
  ansible.builtin.unarchive:
    src: "{{ARTIFACT_ZIP_URL}}"
    dest:  /usr/share/nginx
    remote_src: yes

- name: rename content directory
  ansible.builtin.shell: mv /usr/share/nginx/static /usr/share/nginx/html

- name: Update nginx configuration
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  notify: Restart nginx

- name: start nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started

#- name: include common role for OS prereqs
#  ansible.builtin.include_role:
#    name: common
#    tasks_from: os
#
#- name: Install nginx
#  ansible.builtin.yum:
#    name: nginx
#    state: present
#
#- name: include common role for az devops artifacts
#  ansible.builtin.include_role:
#    name: common
#    tasks_from: download-from-az-artifacts.yml
#  vars:
#    ARTIFACT_PATH: "/usr/share/nginx"
#    BUSER: "root"
#
#
#- name: rename content directory
#  ansible.builtin.shell: mv /usr/share/nginx/static /usr/share/nginx/html
#
#- name: Update nginx configuration
#  ansible.builtin.template:
#    src: roboshop.conf
#    dest: /etc/nginx/default.d/roboshop.conf
#  notify: Restart nginx
#
#- name: start nginx
#  ansible.builtin.systemd:
#    name: nginx
#    enabled: yes
#    state: started