- name: Demo on variables
  hosts: all
  vars:
    URL: vars.sample.com
  tasks:
    - name: Print the variables
      ansible.builtin.debug:
       msg: Hello {{ URL }}

    - name: Print the variable again
      ansible.builtin.debug:
        msg: Hello {{ URL }}

    - name: Print local variable
      ansible.builtin.debug:
        msg: Hello {{ URL }}
      vars:
        URL: tasks.google.com
#observation:
#1. vars declared on play level can be accessed by any task in the play.
#2. One play variables cannot be accessed by another play by default.
#3. local variables are having higher precedence that global variables.
#some times we need t load variables from a file
#vars_files are having higher precedence than vars
# Command line variables with - e option have highest precedence


- name: Demo on variables from files
  hosts: all
  vars_files:
    - vars.yml
  vars:
    URL: vars.sample.com
  vars_prompt:
    - name: COURSE_NAME
      prompt: Enter tne course name
      private: no
  tasks:
    - name: Print variables
      ansible.builtin.debug:
        msg: HelloGGG {{ URL }}
    - name: Print course
      ansible.builtin.debug:
        msg: Welcome to {{ COURSE_NAME }} Training

#Things to explore- we can define variables in the inventory file also, explore this option
