- name: Demo on variables
  hosts: all
  vars:
    URL: vars.sample.com
  tasks:
    - name: Print the variables
      ansible.builtin.debug:
       msg: Hello {{ URL }}

    - name: Print the variable again
      ansible.builtin.debug:
        msg: Hello {{ URL }}

    - name: Print local variable
      ansible.builtin.debug:
        msg: Hello {{ URL }}
      vars:
        URL: tasks.google.com
#observation:
#1. vars declared on play level can be accessed by any task in the play
#2. One play variables cannot be accessed by another play by default
