- name: demo on facts
  hosts: all
  gather_facts: false
  tasks:
    - name: Print the hostname
      ansible.builtin.debug:
        msg: "{{ ansible_fqdn }}"

#additional facts can also be added by node, by configuring the facts. BTW this is very very less used option
#https://serverascode.com/2015/01/27/ansible-custom-facts.html




