- name: setup roboshop project
  hosts: all
  vars:
    DOMAIN: devopsnik.tk
  become: yes
  #become is nothing but a sudo in CLI. Also this become can be used in task level also
  tasks:
    - name: load cart role
      import_role:
        name: cart
      when: component == "cart"
      tags:
        - cart
    - name: load catalogue role
      import_role:
        name: catalogue
      when: component == "catalogue"
      tags:
        - catalogue
    - name: load user role
      import_role:
        name: user
      when: component == "user"
      tags:
        - user
    - name: load shipping role
      import_role:
        name: shipping
      when: component == "shipping"
      tags:
        - shipping
#    - name: load payment role
#      import_role:
#        name: payment
#      when: component == "payment"
#    - name: load frontend role
#      import_role:
#        name: frontend
#      when: component == "frontend"