- name: setup roboshop project
  hosts: all
  tasks:
    - name: load cart role
      import_role:
        name: cart
      when: component == "cart"
    - name: load catalogue role
      import_role:
        name: catalogue
      when: component == "catalogue"
    - name: load user role
      import_role:
        name: user
      when: component == "user"
    - name: load shipping role
      import_role:
        name: shipping
      when: component == "shipping"
    - name: load payment role
      import_role:
        name: payment
      when: component == "payment"
    - name: load frontend role
      import_role:
        name: frontend
      when: component == "frontend"