- name: include common role for OS prereqs
  ansible.builtin.include_role:
    name: common
    tasks_from: os

- name: copy my sql repo file
  ansible.builtin.template:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: remove mariadb libs
  ansible.builtin.yum:
    name: mariadb-libs
    state: absent

- name: install mysql
  ansible.builtin.yum:
    name: mysql-community-server
    state: present

- name: start mysql
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes
- name: grab the defaul root password
  ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
  register: DEFAULT_PASS

- name: set the new password
  ansible.builtin.shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{MYSQL_PASS}}':" | mysql --connect-expired-password -u root -p'{{DEFAULT_PASS.stdout}}'
