- name: include common role for OS prereqs
  ansible.builtin.include_role:
    name: common
    tasks_from: os
- name: install erlang
  ansible.builtin.yum:
    name: https://packages.erlang-solutions.com/erlang/rpm/centos/7/x86_64/esl-erlang_22.3-1~centos~7_amd64.rpm
    # old version https://packages.erlang-solutions.com/erlang/rpm/centos/7/x86_64/esl-erlang_22.2.1-1~centos~7_amd64.rpm
    state: present

- name: set up yum repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: install rabbitMQ
  ansible.builtin.yum:
    name: rabbitmq-server
    state: present

- name: stast rabbitMQ
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: create app ser in rabbitmq
  ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123 ; rabbitmqctl set_user_tags roboshop administrator ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"