- name: include common role for OS prereqs
  ansible.builtin.include_role:
    name: common
    tasks_from: os

- name: copy mongo repo file
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: present

- name: update mongodb configuration file
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start mongodb
  ansible.builtin.systemd:
    name: mongod
    state: started
    enabled: yes

- name: download and unzip/unarchive {{COMPONENT}} on a remote machine
  ansible.builtin.unarchive:
    src: "{{ARTIFACT_ZIP_URL}}"
    dest:  /tmp
    remote_src: yes

- name: load schema
  ansible.builtin.shell: mongo < catalogue.js ; mongo < users.js
  