- name: install node js packages
  ansible.builtin.yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present
- name: create application user
 user:
   ansible.builtin.user: roboshop

